repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace #performs trailing whitespace check and removal
      - id: end-of-file-fixer #ensures that a file ends with a newline
      - id: check-yaml #checks yaml files for parseable syntax
      - id: check-added-large-files #prevents large files from being added to git
      - id: no-commit-to-branch #prevents committing to specified branches
        args: [--branch, main, --branch, master, --branch, prod]
        stages: [push] #only run this hook on push events

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--config=pyproject.toml]

  - repo: https://github.com/PyCQA/pylint
    rev: v3.2.0
    hooks:
      - id: pylint
        args: [--rcfile=pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [
          --no-strict-optional,
          --ignore-missing-imports,
          --config-file=./pyproject.toml,
          --disable-error-code=misc
        ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-path=pyproject.toml]
